server:
    interface: 0.0.0.0
    interface: 10.10.0.2
    port: 53

    access-control: 127.0.0.0/8 allow
    access-control: 10.10.0.0/24 allow
    access-control: 10.10.1.0/24 allow

    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    hide-identity: yes
    hide-version: yes

    prefetch: yes
    qname-minimisation: yes

    
    local-zone: "cad.internal." static
    local-data: "dns1.cad.internal. IN A 10.10.0.3"
    local-data: "pve1.cad.internal. IN A 10.18.164.185"
    local-data: "pve2.cad.internal. IN A 10.18.164.182"
    local-data: "pve3.cad.internal. IN A 10.18.164.181"
    local-data: "pve4.cad.internal. IN A 10.18.164.180"
    local-data: "pve5.cad.internal. IN A 10.18.164.167"
    local-data: "pve6.cad.internal. IN A 10.18.164.166"
    local-data: "pve7.cad.internal. IN A 10.18.164.165"
    local-data: "pve8.cad.internal. IN A 10.18.164.164"
    local-data: "pve9.cad.internal. IN A 10.18.164.163"
    local-data: "pve10.cad.internal. IN A 10.18.164.162"
    local-data: "pve11.cad.internal. IN A 10.18.164.161"
